services:
    dmzx.setforumwidth.listener:
        class: dmzx\setforumwidth\event\listener
        arguments:
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
